name: Deploy to Render

permissions:
  contents: read
  deployments: write

on:
  workflow_run:
    workflows:
      - "CI-Build"
    types:
      - completed

concurrency:
  group: render
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: render
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.6
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: true # Optional: Clear Render's build cache
          wait_deploy: true
          github_deployment: true
          deployment_environment: "production" # check value
          github_token: ${{ secrets.GITHUB_TOKEN }}
