name: Deploy to Render

permissions:
  contents: read
  deployments: write

on:
  push:
    tags:
      - v**

concurrency:
  group: render
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: render
    steps:
      - name: Deploy to render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"

      #- uses: JorgeLNJunior/render-deploy@v1.4.6
      #  with:
      #    service_id: ${{ secrets.RENDER_SERVICE_ID }}
      #    api_key: ${{ secrets.RENDER_API_KEY }}
      #    clear_cache: true # Optional: Clear Render's build cache
      #    wait_deploy: true
      #    github_deployment: true
      #    deployment_environment: "production"
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
